"""Used to provide a dict mapping unclear IDs to recognizable skill names"""

skill_progress_markers = {
    "AdvancedCook1": "Advanced Cookbook (Level 1)",
    "AdvancedCook2": "Advanced Cookbook (Level 2)",
    "AdvancedCook3": "Advanced Cookbook (Level 3)",
    "AdvancedFurnitureCrafter1": "Furniture Crafting",
    "AdventurersCookbook1": "Adventurer's Cookbook (Level 1)",
    "AdventurersCookbook2": "Adventurer's Cookbook (Level 2)",
    "AdventurersCookbook3": "Adventurer's Cookbook (Level 3)",
    "Alchemy1": "Alchemy Table (skill)",
    "Alchemy2": "Alchemy Table (skill)",
    "Alchemy3": "Alchemy Table (skill)",
    "BeeBox1": "Beekeeper (Level 1)",
    "BeeBox2": "Beekeeper (Level 2)",
    "BeeBox3": "Beekeeper",
    "BeginnerCook1": "Beginner Cookbook (Level 1)",
    "BeginnerCook2": "Beginner Cookbook (Level 2)",
    "BeginnerCook3": "Beginner Cookbook (Level 3)",
    "IceCreamMaker1": "Ice Cream Maker (Level 1)",
    "IceCreamMaker2": "Ice Cream Maker (Level 2)",
    "JamMake2": "Jam Maker (Level 2)",
    "JamMaker1": "Jam Maker",
    "Keg1": "Wooden Keg",
    "ManaTome": "Tomes of Mana (Level 2)",
    "ManaTome1": "Tomes of Mana (Level 2)",
    "MiningAccessories1": "Jewel Crafter",
    "MiningArmor1": "Outfitter (Level 1)",
    "MiningArmor2": "Outfitter (Level 2)",
    "MiningSkillTome": "asdf",
    "SeedMaker1": "Seed Maker",
    "SellPortal1": "Portal Crafter",
    "SkillTome1": "Tomes of Skill",
    "SnaccoonMailC": "Pen-Pals (third letter)",
}
